version: '3.8'

services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./tests:/app/tests:ro
      - ./app:/app/app:ro
      - ./TG2_tests.csv:/app/TG2_tests.csv:ro
      - ./requirements.txt:/app/requirements.txt:ro
      - ./pytest.ini:/app/pytest.ini:ro
    working_dir: /app
    command: ["python", "-m", "pytest", "tests/", "-v", "--tb=short"]
    profiles:
      - test

  test-runner-coverage:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./tests:/app/tests:ro
      - ./app:/app/app:ro
      - ./TG2_tests.csv:/app/TG2_tests.csv:ro
      - ./requirements.txt:/app/requirements.txt:ro
      - ./pytest.ini:/app/pytest.ini:ro
      - ./coverage-reports:/app/coverage-reports
    working_dir: /app
    command: ["python", "-m", "pytest", "tests/", "-v", "--cov=app", "--cov-report=html:coverage-reports/html", "--cov-report=term-missing"]
    profiles:
      - test
    depends_on:
      - test-runner

  test-runner-parallel:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./tests:/app/tests:ro
      - ./app:/app/app:ro
      - ./TG2_tests.csv:/app/TG2_tests.csv:ro
      - ./requirements.txt:/app/requirements.txt:ro
      - ./pytest.ini:/app/pytest.ini:ro
    working_dir: /app
    command: ["python", "-m", "pytest", "tests/", "-v", "-n", "auto", "--tb=short"]
    profiles:
      - test
    depends_on:
      - test-runner

  test-runner-unit:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./tests:/app/tests:ro
      - ./app:/app/app:ro
      - ./TG2_tests.csv:/app/TG2_tests.csv:ro
      - ./requirements.txt:/app/requirements.txt:ro
      - ./pytest.ini:/app/pytest.ini:ro
    working_dir: /app
    command: ["python", "-m", "pytest", "tests/", "-v", "-m", "unit", "--tb=short"]
    profiles:
      - test
    depends_on:
      - test-runner

  test-runner-integration:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./tests:/app/tests:ro
      - ./app:/app/app:ro
      - ./TG2_tests.csv:/app/TG2_tests.csv:ro
      - ./requirements.txt:/app/requirements.txt:ro
      - ./pytest.ini:/app/pytest.ini:ro
    working_dir: /app
    command: ["python", "-m", "pytest", "tests/", "-v", "-m", "integration", "--tb=short"]
    profiles:
      - test
    depends_on:
      - test-runner
