services:
  bdq-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8080
      - PYTHONPATH=/app
      - BDQ_PY4J_GATEWAY_JAR=/opt/bdq/bdq-py4j-gateway.jar
      - BDQ_JAVA_OPTS=-Xms256m -Xmx1024m
      - GMAIL_SEND=test
      - HMAC_SECRET=test-secret
      - DISCORD_WEBHOOK=test
      - GOOGLE_API_KEY=test
    volumes:
      # Mount test data for testing
      - ./tests:/app/tests:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Test service for running tests
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - BDQ_PY4J_GATEWAY_JAR=/opt/bdq/bdq-py4j-gateway.jar
      - BDQ_JAVA_OPTS=-Xms256m -Xmx1024m
      - GMAIL_SEND=test
      - HMAC_SECRET=test-secret
      - DISCORD_WEBHOOK=test
      - GOOGLE_API_KEY=test
    volumes:
      - ./tests:/app/tests:ro
      - ./app:/app/app:ro
      - ./requirements.txt:/app/requirements.txt:ro
    working_dir: /app
    command: ["python", "-m", "pytest", "tests/", "-v", "--tb=short"]
    profiles:
      - test
    depends_on:
      - bdq-app
