version: "3.9"

services:
  worker:
    build: .
    command: uvicorn bdq_multi.worker:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1

  cli:
    build: .
    entrypoint: ["bdq-multi"]
    command: ["--help"]
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1

